version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:5001
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    environment:
      - GraphConfig__Uri=bolt://db
    links: 
      - db
  
  db:
    image: neo4j:4.0.3
    ports: 
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_connector_https_advertised__addres=localhost:7473
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_AUTH=none
    volumes:
      - $HOME/neo4j/data:/data
