dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "**/bin/**/*"
  - "**/obj/**/*"
  - ".typo-ci.yml"
  - "**/.github/**/*"
  - "**/.devcontainer/**/*"

# Any typos we should ignore?
excluded_words:
  - typoci
  - sln
  - dotnetcore
  - Dtos
  - drawio
  - msjsdiag
  - ms-dotnettools
  - csharp
  - mcr
  - devcontainer
  
# Would you like filenames to also be spellchecked?
spellcheck_filenames: true