version: '3.4'

services:
  dependencies.graph.api:
    image: ${DOCKER_REGISTRY-}dependencies.graph.api
    build:
      context: .
      dockerfile: ../Dependencies.Graph.Api/Dockerfile
    ports: 
      - 5000:80
      - 5001:443
    environment:
      - GraphConfig__Uri=bolt://db
      - ASPNETCORE_URLS=http://*:80;https://*:443
    links: 
      - db
  
  db:
    image: neo4j:4.0.3
    
    ports: 
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_connector_https_advertised__addres=localhost:7473
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_AUTH=none
    volumes:
      - $HOME/neo4j/data:/data
   