name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
        source-url: https://nuget.pkg.github.com/xclemence/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Install dependencies
      run: dotnet restore Dependencies.Graph.Services.sln
      working-directory: src
    
    - name: Build
      run: dotnet build Dependencies.Graph.Services.sln --configuration Release --no-restore
      working-directory: src
    
    - name: Build the Docker image
      run: docker build . --file Dependencies.Graph.Api/Dockerfile --tag dependencies_graph_api:$(date +%s)
      working-directory: src

    - name: Publish nuget package
      run: dotnet nuget push "*.nupkg"
      working-directory: src/Dependencies.Graph.Dtos/bin/Release

