name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    outputs:
      buildVersion: ${{ steps.gitversion.outputs.nuGetVersionV2  }}

    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
        source-url: https://nuget.pkg.github.com/xclemence/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
          versionSpec: '5.2.x'
    
    - name: Install dependencies
      run: dotnet restore Dependencies.Graph.Services.sln
      working-directory: src
    
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.2
    
    - name: Build
      run: dotnet build Dependencies.Graph.Services.sln --configuration Release --no-restore /p:VersionSuffix=${{ steps.gitversion.outputs.preReleaseTag }} /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2  }}
      working-directory: src
    
    - name: Test
      run: dotnet test Dependencies.Graph.Services.sln --configuration Release
      working-directory: src
      
    - uses: actions/upload-artifact@v2
      with:
        name: Dtos
        path: src/Dependencies.Graph.Dtos/bin/Release
    
    - name: Build the Docker image
      run: docker build . --file Dependencies.Graph.Api/Dockerfile --tag dependencies_graph_api
      working-directory: src

    - name: Publish Nuget package
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: dotnet nuget push **/*.nupkg --skip-duplicate --no-symbols true
   
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
        source-url: https://nuget.pkg.github.com/xclemence/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Publish docker image
      uses: docker/build-push-action@v1 
      #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/dependencies-graph-api
        tag_with_ref: true
        tag: v${{needs.build.buildVersion}}
        dockerfile: Dependencies.Graph.Api/Dockerfile
      
      

    
